spring:
  # 데이터베이스 연결 설정
  datasource: # 여러 DBaaS에서 가져오기
    url: ${DB_URL} # 데이터베이스 URL
    username: ${DB_USER} # 데이터베이스 사용자 이름
    password: ${DB_PASSWORD} # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버 클래스 이름
#    driver-class-name: org.postgresql.Driver # PostgreSQL 드라이버 클래스 이름
# 로깅 설정
logging:
  level:
    org.example.bootrest.model.mapper: DEBUG # mapper 패키지의 로깅 레벨을 DEBUG로 설정 (DEV)
    # org.example.bootrest.model.mapper: ERROR # mapper 패키지의 로깅 레벨을 ERROR로 설정
    # 너무 쓸데없는 많은 로그 방지